"""add company related tables

Revision ID: a55ac23a2187
Revises: 
Create Date: 2025-08-09 04:21:25.605962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a55ac23a2187'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), server_default='', nullable=False),
    sa.Column('current_employee_count', sa.Integer(), nullable=True),
    sa.Column('current_investment_total', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('current_stage', sa.String(length=20), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('ipo_date', sa.DateTime(), nullable=True),
    sa.Column('total_investment', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_name_en'), 'companies', ['name_en'], unique=False)
    op.create_table('company_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_aliases_alias'), 'company_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_company_aliases_company_id'), 'company_aliases', ['company_id'], unique=False)
    op.create_table('company_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('llm_context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('origin_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_date', 'company_snapshots', ['company_id', 'reference_date'], unique=False)
    op.create_index(op.f('ix_company_snapshots_company_id'), 'company_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_snapshots_reference_date'), 'company_snapshots', ['reference_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_snapshots_reference_date'), table_name='company_snapshots')
    op.drop_index(op.f('ix_company_snapshots_company_id'), table_name='company_snapshots')
    op.drop_index('idx_company_date', table_name='company_snapshots')
    op.drop_table('company_snapshots')
    op.drop_index(op.f('ix_company_aliases_company_id'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_alias'), table_name='company_aliases')
    op.drop_table('company_aliases')
    op.drop_index(op.f('ix_companies_name_en'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
