"""Add news related tables

Revision ID: b651854be18f
Revises: a18fa5cacf68
Create Date: 2025-08-12 18:44:22.043257

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b651854be18f"
down_revision: Union[str, Sequence[str], None] = "a18fa5cacf68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_chunks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("contents", sa.Text(), nullable=False),
        sa.Column(
            "vector", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column("link", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chunk_hnsw",
        "news_chunks",
        ["vector"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"vector": "vector_cosine_ops"},
    )
    op.create_index(
        "idx_news_chunk_created_at_company_id",
        "news_chunks",
        ["created_at", "company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_chunks_company_id"), "news_chunks", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_news_chunks_created_at"), "news_chunks", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_news_chunks_link"), "news_chunks", ["link"], unique=False)
    op.create_index(
        op.f("ix_news_chunks_title"), "news_chunks", ["title"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_news_chunks_title"), table_name="news_chunks")
    op.drop_index(op.f("ix_news_chunks_link"), table_name="news_chunks")
    op.drop_index(op.f("ix_news_chunks_created_at"), table_name="news_chunks")
    op.drop_index(op.f("ix_news_chunks_company_id"), table_name="news_chunks")
    op.drop_index("idx_news_chunk_created_at_company_id", table_name="news_chunks")
    op.drop_index(
        "idx_chunk_hnsw",
        table_name="news_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"vector": "vector_cosine_ops"},
    )
    op.drop_table("news_chunks")
    # ### end Alembic commands ###
