"""Add columns to companies table

Revision ID: d97a2c8d4a9b
Revises: f946568f6b8e
Create Date: 2025-08-10 15:41:03.780794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97a2c8d4a9b'
down_revision: Union[str, Sequence[str], None] = 'f946568f6b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('biz_description', sa.String(length=255), server_default='', nullable=False))
    op.add_column('companies', sa.Column('stage', sa.String(length=32), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'stage')
    op.drop_column('companies', 'biz_description')
    # ### end Alembic commands ###
