"""Add company related tables

Revision ID: e260f7b1ea8e
Revises: 
Create Date: 2025-08-11 22:24:11.167059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e260f7b1ea8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('external_id', sa.String(length=16), nullable=False))
    op.add_column('companies', sa.Column('employee_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_companies_external_id'), 'companies', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_external_id'), table_name='companies')
    op.drop_column('companies', 'employee_count')
    op.drop_column('companies', 'external_id')
    # ### end Alembic commands ###
